import { Category, MenuSection, Order, Restaurant } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'Pizza', icon: '🍕', slug: 'pizza' },
  { id: '2', name: 'Hambúrguer', icon: '🍔', slug: 'hamburger' },
  { id: '3', name: 'Japonesa', icon: '🍣', slug: 'japanese' },
  { id: '4', name: 'Brasileira', icon: '🍖', slug: 'brazilian' },
  { id: '5', name: 'Açaí', icon: '🫐', slug: 'acai' },
  { id: '6', name: 'Árabe', icon: '🥙', slug: 'arabic' },
  { id: '7', name: 'Mexicana', icon: '🌮', slug: 'mexican' },
  { id: '8', name: 'Sorvete', icon: '🍦', slug: 'ice-cream' },
  { id: '9', name: 'Saudável', icon: '🥗', slug: 'healthy' },
  { id: '10', name: 'Bebidas', icon: '🥤', slug: 'drinks' },
];

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: '1',
    name: 'Domino\'s Pizza',
    slug: 'dominos-pizza',
    logo: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&h=400&fit=crop',
    category: 'Pizza',
    categoryIcon: '🍕',
    rating: 4.7,
    reviewCount: 1823,
    deliveryTime: 35,
    deliveryFee: 5.99,
    minOrder: 25,
    distance: 1.2,
    isOpen: true,
    tags: ['Pizza', 'Rápido'],
  },
  {
    id: '2',
    name: 'McDonald\'s',
    slug: 'mcdonalds',
    logo: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&h=400&fit=crop',
    category: 'Hambúrguer',
    categoryIcon: '🍔',
    rating: 4.5,
    reviewCount: 3210,
    deliveryTime: 25,
    deliveryFee: 0,
    minOrder: 15,
    distance: 0.8,
    isOpen: true,
    tags: ['Hambúrguer', 'Frete grátis'],
  },
  {
    id: '3',
    name: 'Outback Steakhouse',
    slug: 'outback',
    logo: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800&h=400&fit=crop',
    category: 'Brasileira',
    categoryIcon: '🍖',
    rating: 4.8,
    reviewCount: 987,
    deliveryTime: 50,
    deliveryFee: 8.99,
    minOrder: 40,
    distance: 3.5,
    isOpen: true,
    tags: ['Carnes', 'Premium'],
  },
  {
    id: '4',
    name: 'Sushi Leblon',
    slug: 'sushi-leblon',
    logo: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=800&h=400&fit=crop',
    category: 'Japonesa',
    categoryIcon: '🍣',
    rating: 4.9,
    reviewCount: 542,
    deliveryTime: 45,
    deliveryFee: 6.99,
    minOrder: 50,
    distance: 2.1,
    isOpen: true,
    tags: ['Sushi', 'Premium'],
  },
  {
    id: '5',
    name: 'Burger King',
    slug: 'burger-king',
    logo: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=800&h=400&fit=crop',
    category: 'Hambúrguer',
    categoryIcon: '🍔',
    rating: 4.3,
    reviewCount: 2100,
    deliveryTime: 30,
    deliveryFee: 3.99,
    minOrder: 20,
    distance: 1.5,
    isOpen: false,
    tags: ['Hambúrguer', 'Rápido'],
  },
  {
    id: '6',
    name: 'Açaí do Norte',
    slug: 'acai-do-norte',
    logo: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=100&h=100&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?w=800&h=400&fit=crop',
    category: 'Açaí',
    categoryIcon: '🫐',
    rating: 4.6,
    reviewCount: 765,
    deliveryTime: 20,
    deliveryFee: 2.99,
    minOrder: 15,
    distance: 0.5,
    isOpen: true,
    tags: ['Açaí', 'Saudável'],
  },
];

export const MOCK_MENU_SECTIONS: MenuSection[] = [
  {
    title: '🔥 Mais Pedidos',
    data: [
      {
        id: 'm1',
        name: 'X-Burguer Clássico',
        description: 'Pão brioche, carne angus 180g, queijo cheddar, alface, tomate e molho especial',
        price: 28.9,
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',
        restaurantId: '2',
        isAvailable: true,
        calories: 650,
      },
      {
        id: 'm2',
        name: 'Double Smash Burguer',
        description: 'Dois smash patties 90g, queijo americano duplo, picles, cebola caramelizada',
        price: 38.9,
        image: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400&h=300&fit=crop',
        restaurantId: '2',
        isAvailable: true,
        calories: 820,
      },
    ],
  },
  {
    title: '🍔 Hambúrgueres',
    data: [
      {
        id: 'm3',
        name: 'Chicken Crispy',
        description: 'Frango empanado crocante, molho honey mustard, coleslaw',
        price: 25.9,
        image: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=400&h=300&fit=crop',
        restaurantId: '2',
        isAvailable: true,
        calories: 580,
      },
      {
        id: 'm4',
        name: 'Veggie Burguer',
        description: 'Blend de grão de bico, cogumelo e ervas, queijo vegano, rúcula',
        price: 27.9,
        image: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=400&h=300&fit=crop',
        restaurantId: '2',
        isAvailable: true,
        calories: 420,
      },
    ],
  },
  {
    title: '🍟 Acompanhamentos',
    data: [
      {
        id: 'm5',
        name: 'Batata Frita Pequena',
        description: 'Batata frita crocante com sal',
        price: 10.9,
        image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=300&fit=crop',
        restaurantId: '2',
        isAvailable: true,
        calories: 320,
      },
      {
        id: 'm6',
        name: 'Onion Rings',
        description: 'Anéis de cebola empanados com molho barbecue',
        price: 15.9,
        image: 'https://images.unsplash.com/photo-1639024471283-03518883512d?w=400&h=300&fit=crop',
        restaurantId: '2',
        isAvailable: true,
        calories: 410,
      },
    ],
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord1',
    restaurantId: '2',
    restaurantName: 'McDonald\'s',
    restaurantLogo: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=100&h=100&fit=crop',
    items: [
      { item: MOCK_MENU_SECTIONS[0].data[0], quantity: 1 },
      { item: MOCK_MENU_SECTIONS[2].data[0], quantity: 2 },
    ],
    total: 49.70,
    deliveryFee: 0,
    status: 'delivered',
    address: {
      id: 'addr1',
      label: 'Casa',
      street: 'Rua das Flores',
      number: '123',
      neighborhood: 'Jardim América',
      city: 'São Paulo',
      state: 'SP',
      zipCode: '01310-100',
    },
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
];
